plugins { id 'com.android.application' }

android {
    namespace 'com.floryflowers.live'
    compileSdk 35

    defaultConfig {
        applicationId "com.floryflowers.live"
        minSdk 24
        targetSdk 35
        versionCode 22
        versionName "1.22.1"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
