import { useEffect, useMemo, useState } from 'react';
import { useLocales } from 'expo-localization';
import AsyncStorage from '@react-native-async-storage/async-storage';

export const SUPPORTED_LANGUAGES = ["ro","en","de","es","fr","it","pt","nl","pl","uk","ru","tr","el","hu","cs","sk","bg","sr","hr","sl","ar","he","zh","ja","ko","hi"] as const;
export type SupportedLanguage = typeof SUPPORTED_LANGUAGES[number];

export const LANGUAGE_NAMES: Record<SupportedLanguage, string> = {
  ro:'Română', en:'English', de:'Deutsch', es:'Español', fr:'Français', it:'Italiano',
  pt:'Português', nl:'Nederlands', pl:'Polski', uk:'Українська', ru:'Русский', tr:'Türkçe',
  el:'Ελληνικά', hu:'Magyar', cs:'Čeština', sk:'Slovenčina', bg:'Български', sr:'Srpski',
  hr:'Hrvatski', sl:'Slovenščina', ar:'العربية', he:'עברית', zh:'中文', ja:'日本語',
  ko:'한국어', hi:'हिन्दी'
};

const LANGUAGE_OVERRIDE_KEY = 'scalpAtlas.language.override.v1';

const translations = {
  "ro": {
    "models": "modele",
    "guideQuick": "GHID RAPID",
    "initializingCamera": "Inițializez camera…",
    "cameraPermission": "Camera este necesară pentru analiza LIVE a graficului.",
    "allowCamera": "PERMITE CAMERA",
    "quickStart": "PORNIRE RAPIDĂ",
    "quickSub": "3 pași pentru o analiză LIVE corectă",
    "step1": "Îndreaptă camera spre graficul de tranzacționare de pe al doilea dispozitiv.",
    "step2": "Păstrează vizibile lumânările, prețurile și timeframe-ul, apoi fixează cadrul.",
    "step3": "Pornește CAMERA LIVE și așteaptă confirmarea 2/2 înainte de BUY sau SELL.",
    "understood": "AM ÎNȚELES",
    "timeframeAuto": "TIMEFRAME AUTO",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "APASĂ PENTRU PORNIRE",
    "activeAuto": "ACTIVĂ • ANALIZĂ AUTOMATĂ",
    "directionWindow": "FEREASTRĂ DIRECȚIE",
    "lastSignals": "ULTIMELE SEMNALE",
    "history": "ISTORIC",
    "stats": "STATISTICI",
    "total": "TOTAL",
    "journal": "JURNAL",
    "wait": "AȘTEAPTĂ",
    "noSignal": "FĂRĂ SEMNAL CLAR",
    "pending": "ÎN AȘTEPTARE",
    "recentEmpty": "Primele semnale vor apărea aici după pornirea LIVE.",
    "noHistory": "Nu există încă analize LIVE salvate.",
    "journalSub": "Marchează manual rezultatul semnalelor BUY/SELL și adaugă sumă/notă.",
    "noJournal": "Nu există încă semnale BUY/SELL pentru jurnal.",
    "delete": "ȘTERGE",
    "result": "REZULTAT LIVE",
    "model": "Model",
    "score": "Scor",
    "expiry": "Expirare recomandată",
    "direction": "Durată estimată direcție",
    "camera": "Cameră",
    "engine": "Motor",
    "ready": "PREGĂTIT",
    "initializing": "INIȚIALIZARE",
    "chartDetected": "GRAFIC DETECTAT • ANALIZĂ ACTIVĂ",
    "chartMissing": "GRAFIC NEDETECTAT",
    "waitingChart": "AȘTEPT GRAFIC PENTRU ANALIZĂ",
    "positionCamera": "POZIȚIONEAZĂ CAMERA",
    "frameFixed": "CADRU FIXAT",
    "frameHere": "ÎNCADREAZĂ GRAFICUL AICI",
    "monitoring": "URMĂRIRE ACTIVĂ",
    "readyLive": "GATA DE LIVE",
    "disclaimer": "Semnalele sunt estimări, nu garanții. Decizia aparține utilizatorului."
  },
  "en": {
    "models": "models",
    "guideQuick": "QUICK GUIDE",
    "initializingCamera": "Initializing camera…",
    "cameraPermission": "Camera access is required for LIVE chart analysis.",
    "allowCamera": "ALLOW CAMERA",
    "quickStart": "QUICK START",
    "quickSub": "3 steps for correct LIVE analysis",
    "step1": "Point the camera at the trading chart on the second device.",
    "step2": "Keep candles, prices and timeframe visible, then lock the frame.",
    "step3": "Start CAMERA LIVE and wait for 2/2 confirmation before BUY or SELL.",
    "understood": "GOT IT",
    "timeframeAuto": "AUTO TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "TAP TO START",
    "activeAuto": "ACTIVE • AUTOMATIC ANALYSIS",
    "directionWindow": "DIRECTION WINDOW",
    "lastSignals": "LATEST SIGNALS",
    "history": "HISTORY",
    "stats": "STATISTICS",
    "total": "TOTAL",
    "journal": "JOURNAL",
    "wait": "WAIT",
    "noSignal": "NO CLEAR SIGNAL",
    "pending": "WAITING",
    "recentEmpty": "The first signals will appear here after LIVE starts.",
    "noHistory": "No LIVE analyses have been saved yet.",
    "journalSub": "Manually mark BUY/SELL outcomes and add an amount or note.",
    "noJournal": "There are no BUY/SELL signals in the journal yet.",
    "delete": "DELETE",
    "result": "LIVE RESULT",
    "model": "Model",
    "score": "Score",
    "expiry": "Recommended expiry",
    "direction": "Estimated direction duration",
    "camera": "Camera",
    "engine": "Engine",
    "ready": "READY",
    "initializing": "INITIALIZING",
    "chartDetected": "CHART DETECTED • ANALYSIS ACTIVE",
    "chartMissing": "CHART NOT DETECTED",
    "waitingChart": "WAITING FOR CHART",
    "positionCamera": "POSITION CAMERA",
    "frameFixed": "FRAME LOCKED",
    "frameHere": "FRAME THE CHART HERE",
    "monitoring": "MONITORING ACTIVE",
    "readyLive": "READY FOR LIVE",
    "disclaimer": "Signals are estimates, not guarantees. The user makes the final decision."
  },
  "de": {
    "models": "Modelle",
    "guideQuick": "KURZANLEITUNG",
    "initializingCamera": "Kamera wird initialisiert…",
    "cameraPermission": "Kamerazugriff ist für die LIVE-Chartanalyse erforderlich.",
    "allowCamera": "KAMERA ERLAUBEN",
    "quickStart": "SCHNELLSTART",
    "quickSub": "3 Schritte für eine korrekte LIVE-Analyse",
    "step1": "Richte die Kamera auf den Trading-Chart des zweiten Geräts.",
    "step2": "Kerzen, Preise und Zeitrahmen sichtbar lassen und den Rahmen fixieren.",
    "step3": "CAMERA LIVE starten und vor BUY oder SELL die Bestätigung 2/2 abwarten.",
    "understood": "VERSTANDEN",
    "timeframeAuto": "ZEITRAHMEN AUTO",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "ZUM STARTEN TIPPEN",
    "activeAuto": "AKTIV • AUTOMATISCHE ANALYSE",
    "directionWindow": "RICHTUNGSFENSTER",
    "lastSignals": "LETZTE SIGNALE",
    "history": "VERLAUF",
    "stats": "STATISTIK",
    "journal": "JOURNAL",
    "wait": "WARTEN",
    "delete": "LÖSCHEN",
    "result": "LIVE-ERGEBNIS",
    "model": "Modell",
    "score": "Score",
    "expiry": "Empfohlener Ablauf",
    "direction": "Geschätzte Richtungsdauer",
    "camera": "Kamera",
    "engine": "Engine",
    "ready": "BEREIT",
    "initializing": "INITIALISIERUNG",
    "chartDetected": "CHART ERKANNT • ANALYSE AKTIV",
    "chartMissing": "CHART NICHT ERKANNT",
    "waitingChart": "WARTE AUF CHART",
    "positionCamera": "KAMERA AUSRICHTEN",
    "frameFixed": "RAHMEN FIXIERT",
    "frameHere": "CHART HIER EINRAHMEN",
    "monitoring": "ÜBERWACHUNG AKTIV",
    "readyLive": "BEREIT FÜR LIVE",
    "disclaimer": "Signale sind Schätzungen, keine Garantien. Die Entscheidung trifft der Nutzer."
  },
  "es": {
    "models": "modelos",
    "guideQuick": "GUÍA RÁPIDA",
    "initializingCamera": "Inicializando cámara…",
    "cameraPermission": "Se necesita acceso a la cámara para el análisis LIVE del gráfico.",
    "allowCamera": "PERMITIR CÁMARA",
    "quickStart": "INICIO RÁPIDO",
    "quickSub": "3 pasos para un análisis LIVE correcto",
    "step1": "Apunta la cámara al gráfico de trading del segundo dispositivo.",
    "step2": "Mantén visibles las velas, los precios y el timeframe y fija el encuadre.",
    "step3": "Inicia CAMERA LIVE y espera la confirmación 2/2 antes de BUY o SELL.",
    "understood": "ENTENDIDO",
    "timeframeAuto": "TIMEFRAME AUTO",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "TOCA PARA INICIAR",
    "activeAuto": "ACTIVA • ANÁLISIS AUTOMÁTICO",
    "directionWindow": "VENTANA DE DIRECCIÓN",
    "lastSignals": "ÚLTIMAS SEÑALES",
    "history": "HISTORIAL",
    "stats": "ESTADÍSTICAS",
    "journal": "DIARIO",
    "wait": "ESPERA",
    "delete": "BORRAR",
    "result": "RESULTADO LIVE",
    "model": "Modelo",
    "score": "Puntuación",
    "expiry": "Expiración recomendada",
    "direction": "Duración estimada de la dirección",
    "camera": "Cámara",
    "engine": "Motor",
    "ready": "LISTO",
    "initializing": "INICIALIZANDO",
    "chartDetected": "GRÁFICO DETECTADO • ANÁLISIS ACTIVO",
    "chartMissing": "GRÁFICO NO DETECTADO",
    "waitingChart": "ESPERANDO GRÁFICO",
    "positionCamera": "POSICIONA LA CÁMARA",
    "frameFixed": "ENCUADRE FIJADO",
    "frameHere": "ENCUADRA EL GRÁFICO AQUÍ",
    "monitoring": "SEGUIMIENTO ACTIVO",
    "readyLive": "LISTO PARA LIVE",
    "disclaimer": "Las señales son estimaciones, no garantías. La decisión final es del usuario."
  },
  "fr": {
    "models": "modèles",
    "guideQuick": "GUIDE RAPIDE",
    "initializingCamera": "Initialisation de la caméra…",
    "cameraPermission": "L’accès à la caméra est nécessaire pour l’analyse LIVE du graphique.",
    "allowCamera": "AUTORISER LA CAMÉRA",
    "quickStart": "DÉMARRAGE RAPIDE",
    "quickSub": "3 étapes pour une analyse LIVE correcte",
    "step1": "Pointez la caméra vers le graphique de trading du second appareil.",
    "step2": "Gardez bougies, prix et timeframe visibles, puis verrouillez le cadrage.",
    "step3": "Démarrez CAMERA LIVE et attendez la confirmation 2/2 avant BUY ou SELL.",
    "understood": "COMPRIS",
    "timeframeAuto": "TIMEFRAME AUTO",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "APPUYER POUR DÉMARRER",
    "activeAuto": "ACTIVE • ANALYSE AUTOMATIQUE",
    "directionWindow": "FENÊTRE DE DIRECTION",
    "lastSignals": "DERNIERS SIGNAUX",
    "history": "HISTORIQUE",
    "stats": "STATISTIQUES",
    "journal": "JOURNAL",
    "wait": "ATTENDRE",
    "delete": "SUPPRIMER",
    "result": "RÉSULTAT LIVE",
    "model": "Modèle",
    "score": "Score",
    "expiry": "Expiration recommandée",
    "direction": "Durée estimée de la direction",
    "camera": "Caméra",
    "engine": "Moteur",
    "ready": "PRÊT",
    "initializing": "INITIALISATION",
    "chartDetected": "GRAPHIQUE DÉTECTÉ • ANALYSE ACTIVE",
    "chartMissing": "GRAPHIQUE NON DÉTECTÉ",
    "waitingChart": "EN ATTENTE DU GRAPHIQUE",
    "positionCamera": "POSITIONNER LA CAMÉRA",
    "frameFixed": "CADRAGE VERROUILLÉ",
    "frameHere": "CADREZ LE GRAPHIQUE ICI",
    "monitoring": "SURVEILLANCE ACTIVE",
    "readyLive": "PRÊT POUR LIVE",
    "disclaimer": "Les signaux sont des estimations, pas des garanties. L’utilisateur prend la décision finale."
  },
  "it": {
    "models": "modelli",
    "guideQuick": "GUIDA RAPIDA",
    "initializingCamera": "Inizializzazione fotocamera…",
    "cameraPermission": "L’accesso alla fotocamera è necessario per l’analisi LIVE del grafico.",
    "allowCamera": "CONSENTI FOTOCAMERA",
    "quickStart": "AVVIO RAPIDO",
    "quickSub": "3 passaggi per una corretta analisi LIVE",
    "step1": "Punta la fotocamera sul grafico di trading del secondo dispositivo.",
    "step2": "Mantieni visibili candele, prezzi e timeframe, poi blocca l’inquadratura.",
    "step3": "Avvia CAMERA LIVE e attendi la conferma 2/2 prima di BUY o SELL.",
    "understood": "CAPITO",
    "timeframeAuto": "TIMEFRAME AUTO",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "TOCCA PER AVVIARE",
    "activeAuto": "ATTIVA • ANALISI AUTOMATICA",
    "directionWindow": "FINESTRA DIREZIONE",
    "lastSignals": "ULTIMI SEGNALI",
    "history": "CRONOLOGIA",
    "stats": "STATISTICHE",
    "journal": "DIARIO",
    "wait": "ATTENDI",
    "delete": "ELIMINA",
    "result": "RISULTATO LIVE",
    "model": "Modello",
    "score": "Punteggio",
    "expiry": "Scadenza consigliata",
    "direction": "Durata stimata direzione",
    "camera": "Fotocamera",
    "engine": "Motore",
    "ready": "PRONTO",
    "initializing": "INIZIALIZZAZIONE",
    "chartDetected": "GRAFICO RILEVATO • ANALISI ATTIVA",
    "chartMissing": "GRAFICO NON RILEVATO",
    "waitingChart": "IN ATTESA DEL GRAFICO",
    "positionCamera": "POSIZIONA FOTOCAMERA",
    "frameFixed": "INQUADRATURA BLOCCATA",
    "frameHere": "INQUADRA QUI IL GRAFICO",
    "monitoring": "MONITORAGGIO ATTIVO",
    "readyLive": "PRONTO PER LIVE",
    "disclaimer": "I segnali sono stime, non garanzie. La decisione finale spetta all’utente."
  },
  "pt": {
    "models": "modelos",
    "guideQuick": "GUIA RÁPIDO",
    "initializingCamera": "A inicializar a câmara…",
    "cameraPermission": "É necessário acesso à câmara para a análise LIVE do gráfico.",
    "allowCamera": "PERMITIR CÂMARA",
    "quickStart": "INÍCIO RÁPIDO",
    "quickSub": "3 passos para uma análise LIVE correta",
    "step1": "Aponte a câmara para o gráfico de trading do segundo dispositivo.",
    "step2": "Mantenha velas, preços e timeframe visíveis e fixe o enquadramento.",
    "step3": "Inicie CAMERA LIVE e aguarde a confirmação 2/2 antes de BUY ou SELL.",
    "understood": "ENTENDI",
    "timeframeAuto": "TIMEFRAME AUTO",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "TOQUE PARA INICIAR",
    "activeAuto": "ATIVA • ANÁLISE AUTOMÁTICA",
    "directionWindow": "JANELA DE DIREÇÃO",
    "lastSignals": "ÚLTIMOS SINAIS",
    "history": "HISTÓRICO",
    "stats": "ESTATÍSTICAS",
    "journal": "DIÁRIO",
    "wait": "AGUARDE",
    "delete": "APAGAR",
    "result": "RESULTADO LIVE",
    "model": "Modelo",
    "score": "Pontuação",
    "expiry": "Expiração recomendada",
    "direction": "Duração estimada da direção",
    "camera": "Câmara",
    "engine": "Motor",
    "ready": "PRONTO",
    "initializing": "A INICIALIZAR",
    "chartDetected": "GRÁFICO DETETADO • ANÁLISE ATIVA",
    "chartMissing": "GRÁFICO NÃO DETETADO",
    "waitingChart": "A AGUARDAR GRÁFICO",
    "positionCamera": "POSICIONE A CÂMARA",
    "frameFixed": "ENQUADRAMENTO FIXO",
    "frameHere": "ENQUADRE O GRÁFICO AQUI",
    "monitoring": "MONITORIZAÇÃO ATIVA",
    "readyLive": "PRONTO PARA LIVE",
    "disclaimer": "Os sinais são estimativas, não garantias. A decisão final pertence ao utilizador."
  },
  "nl": {
    "models": "modellen",
    "guideQuick": "SNELLE GIDS",
    "initializingCamera": "Camera initialiseren…",
    "cameraPermission": "Cameratoegang is vereist voor LIVE-grafiekanalyse.",
    "allowCamera": "CAMERA TOESTAAN",
    "quickStart": "SNEL STARTEN",
    "quickSub": "3 stappen voor correcte LIVE-analyse",
    "step1": "Richt de camera op de tradinggrafiek op het tweede apparaat.",
    "step2": "Houd candles, prijzen en timeframe zichtbaar en vergrendel het kader.",
    "step3": "Start CAMERA LIVE en wacht op 2/2 bevestiging vóór BUY of SELL.",
    "understood": "BEGREPEN",
    "timeframeAuto": "AUTO TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "TIK OM TE STARTEN",
    "activeAuto": "ACTIEF • AUTOMATISCHE ANALYSE",
    "directionWindow": "RICHTINGSVENSTER",
    "lastSignals": "LAATSTE SIGNALEN",
    "history": "GESCHIEDENIS",
    "stats": "STATISTIEKEN",
    "journal": "JOURNAAL",
    "wait": "WACHT",
    "delete": "VERWIJDER",
    "result": "LIVE RESULTAAT",
    "model": "Model",
    "score": "Score",
    "expiry": "Aanbevolen vervaltijd",
    "direction": "Geschatte richtingsduur",
    "camera": "Camera",
    "engine": "Engine",
    "ready": "GEREED",
    "initializing": "INITIALISEREN",
    "chartDetected": "GRAFIEK GEDETECTEERD • ANALYSE ACTIEF",
    "chartMissing": "GRAFIEK NIET GEDETECTEERD",
    "waitingChart": "WACHT OP GRAFIEK",
    "positionCamera": "POSITIONEER CAMERA",
    "frameFixed": "KADER VERGRENDELD",
    "frameHere": "PLAATS GRAFIEK HIER",
    "monitoring": "MONITORING ACTIEF",
    "readyLive": "KLAAR VOOR LIVE",
    "disclaimer": "Signalen zijn schattingen, geen garanties. De gebruiker neemt de uiteindelijke beslissing."
  },
  "pl": {
    "models": "modele",
    "guideQuick": "SZYBKI PRZEWODNIK",
    "initializingCamera": "Inicjalizacja kamery…",
    "cameraPermission": "Dostęp do kamery jest wymagany do analizy wykresu LIVE.",
    "allowCamera": "ZEZWÓL NA KAMERĘ",
    "quickStart": "SZYBKI START",
    "quickSub": "3 kroki do poprawnej analizy LIVE",
    "step1": "Skieruj kamerę na wykres handlowy na drugim urządzeniu.",
    "step2": "Pozostaw widoczne świece, ceny i interwał, a następnie zablokuj kadr.",
    "step3": "Uruchom CAMERA LIVE i poczekaj na potwierdzenie 2/2 przed BUY lub SELL.",
    "understood": "ROZUMIEM",
    "timeframeAuto": "AUTO INTERWAŁ",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "DOTKNIJ, ABY URUCHOMIĆ",
    "activeAuto": "AKTYWNA • ANALIZA AUTOMATYCZNA",
    "directionWindow": "OKNO KIERUNKU",
    "lastSignals": "OSTATNIE SYGNAŁY",
    "history": "HISTORIA",
    "stats": "STATYSTYKI",
    "journal": "DZIENNIK",
    "wait": "CZEKAJ",
    "delete": "USUŃ",
    "result": "WYNIK LIVE",
    "model": "Model",
    "score": "Wynik",
    "expiry": "Zalecane wygaśnięcie",
    "direction": "Szacowany czas kierunku",
    "camera": "Kamera",
    "engine": "Silnik",
    "ready": "GOTOWY",
    "initializing": "INICJALIZACJA",
    "chartDetected": "WYKRES WYKRYTY • ANALIZA AKTYWNA",
    "chartMissing": "NIE WYKRYTO WYKRESU",
    "waitingChart": "OCZEKIWANIE NA WYKRES",
    "positionCamera": "USTAW KAMERĘ",
    "frameFixed": "KADR ZABLOKOWANY",
    "frameHere": "UMIEŚĆ WYKRES TUTAJ",
    "monitoring": "MONITOROWANIE AKTYWNE",
    "readyLive": "GOTOWY DO LIVE",
    "disclaimer": "Sygnały są szacunkami, nie gwarancjami. Ostateczna decyzja należy do użytkownika."
  },
  "uk": {
    "models": "моделі",
    "guideQuick": "ШВИДКИЙ ПОСІБНИК",
    "initializingCamera": "Ініціалізація камери…",
    "cameraPermission": "Для LIVE-аналізу графіка потрібен доступ до камери.",
    "allowCamera": "ДОЗВОЛИТИ КАМЕРУ",
    "quickStart": "ШВИДКИЙ СТАРТ",
    "quickSub": "3 кроки для коректного LIVE-аналізу",
    "step1": "Наведіть камеру на торговий графік на другому пристрої.",
    "step2": "Залиште видимими свічки, ціни й таймфрейм, потім зафіксуйте кадр.",
    "step3": "Запустіть CAMERA LIVE і дочекайтеся підтвердження 2/2 перед BUY або SELL.",
    "understood": "ЗРОЗУМІЛО",
    "timeframeAuto": "ТАЙМФРЕЙМ АВТО",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "НАТИСНІТЬ ДЛЯ СТАРТУ",
    "activeAuto": "АКТИВНА • АВТОМАТИЧНИЙ АНАЛІЗ",
    "directionWindow": "ВІКНО НАПРЯМКУ",
    "lastSignals": "ОСТАННІ СИГНАЛИ",
    "history": "ІСТОРІЯ",
    "stats": "СТАТИСТИКА",
    "journal": "ЖУРНАЛ",
    "wait": "ЧЕКАТИ",
    "delete": "ВИДАЛИТИ",
    "result": "LIVE РЕЗУЛЬТАТ",
    "model": "Модель",
    "score": "Оцінка",
    "expiry": "Рекомендований час завершення",
    "direction": "Орієнтовна тривалість напрямку",
    "camera": "Камера",
    "engine": "Модуль",
    "ready": "ГОТОВО",
    "initializing": "ІНІЦІАЛІЗАЦІЯ",
    "chartDetected": "ГРАФІК ВИЯВЛЕНО • АНАЛІЗ АКТИВНИЙ",
    "chartMissing": "ГРАФІК НЕ ВИЯВЛЕНО",
    "waitingChart": "ОЧІКУВАННЯ ГРАФІКА",
    "positionCamera": "РОЗТАШУЙТЕ КАМЕРУ",
    "frameFixed": "КАДР ЗАФІКСОВАНО",
    "frameHere": "РОЗМІСТІТЬ ГРАФІК ТУТ",
    "monitoring": "МОНІТОРИНГ АКТИВНИЙ",
    "readyLive": "ГОТОВО ДО LIVE",
    "disclaimer": "Сигнали є оцінками, а не гарантіями. Остаточне рішення приймає користувач."
  },
  "ru": {
    "models": "моделей",
    "guideQuick": "КРАТКОЕ РУКОВОДСТВО",
    "initializingCamera": "Инициализация камеры…",
    "cameraPermission": "Для LIVE-анализа графика требуется доступ к камере.",
    "allowCamera": "РАЗРЕШИТЬ КАМЕРУ",
    "quickStart": "БЫСТРЫЙ СТАРТ",
    "quickSub": "3 шага для корректного LIVE-анализа",
    "step1": "Наведите камеру на торговый график на втором устройстве.",
    "step2": "Оставьте видимыми свечи, цены и таймфрейм, затем зафиксируйте кадр.",
    "step3": "Запустите CAMERA LIVE и дождитесь подтверждения 2/2 перед BUY или SELL.",
    "understood": "ПОНЯТНО",
    "timeframeAuto": "ТАЙМФРЕЙМ АВТО",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "НАЖМИТЕ ДЛЯ СТАРТА",
    "activeAuto": "АКТИВНА • АВТОМАТИЧЕСКИЙ АНАЛИЗ",
    "directionWindow": "ОКНО НАПРАВЛЕНИЯ",
    "lastSignals": "ПОСЛЕДНИЕ СИГНАЛЫ",
    "history": "ИСТОРИЯ",
    "stats": "СТАТИСТИКА",
    "journal": "ЖУРНАЛ",
    "wait": "ЖДАТЬ",
    "delete": "УДАЛИТЬ",
    "result": "LIVE РЕЗУЛЬТАТ",
    "model": "Модель",
    "score": "Оценка",
    "expiry": "Рекомендуемое истечение",
    "direction": "Оценочная длительность направления",
    "camera": "Камера",
    "engine": "Модуль",
    "ready": "ГОТОВО",
    "initializing": "ИНИЦИАЛИЗАЦИЯ",
    "chartDetected": "ГРАФИК ОБНАРУЖЕН • АНАЛИЗ АКТИВЕН",
    "chartMissing": "ГРАФИК НЕ ОБНАРУЖЕН",
    "waitingChart": "ОЖИДАНИЕ ГРАФИКА",
    "positionCamera": "НАПРАВЬТЕ КАМЕРУ",
    "frameFixed": "КАДР ЗАФИКСИРОВАН",
    "frameHere": "РАЗМЕСТИТЕ ГРАФИК ЗДЕСЬ",
    "monitoring": "МОНИТОРИНГ АКТИВЕН",
    "readyLive": "ГОТОВО К LIVE",
    "disclaimer": "Сигналы являются оценками, а не гарантиями. Окончательное решение принимает пользователь."
  },
  "tr": {
    "models": "model",
    "guideQuick": "HIZLI KILAVUZ",
    "initializingCamera": "Kamera başlatılıyor…",
    "cameraPermission": "LIVE grafik analizi için kamera erişimi gereklidir.",
    "allowCamera": "KAMERAYA İZİN VER",
    "quickStart": "HIZLI BAŞLANGIÇ",
    "quickSub": "Doğru LIVE analiz için 3 adım",
    "step1": "Kamerayı ikinci cihazdaki işlem grafiğine yöneltin.",
    "step2": "Mumları, fiyatları ve zaman dilimini görünür tutup kadrajı kilitleyin.",
    "step3": "CAMERA LIVE'ı başlatın ve BUY/SELL öncesi 2/2 onayı bekleyin.",
    "understood": "ANLADIM",
    "timeframeAuto": "OTOMATİK ZAMAN DİLİMİ",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "BAŞLATMAK İÇİN DOKUN",
    "activeAuto": "AKTİF • OTOMATİK ANALİZ",
    "directionWindow": "YÖN PENCERESİ",
    "lastSignals": "SON SİNYALLER",
    "history": "GEÇMİŞ",
    "stats": "İSTATİSTİK",
    "journal": "GÜNLÜK",
    "wait": "BEKLE",
    "delete": "SİL",
    "result": "LIVE SONUÇ",
    "model": "Model",
    "score": "Skor",
    "expiry": "Önerilen bitiş",
    "direction": "Tahmini yön süresi",
    "camera": "Kamera",
    "engine": "Motor",
    "ready": "HAZIR",
    "initializing": "BAŞLATILIYOR",
    "chartDetected": "GRAFİK ALGILANDI • ANALİZ AKTİF",
    "chartMissing": "GRAFİK ALGILANMADI",
    "waitingChart": "GRAFİK BEKLENİYOR",
    "positionCamera": "KAMERAYI KONUMlandır",
    "frameFixed": "KADRAJ KİLİTLİ",
    "frameHere": "GRAFİĞİ BURAYA KADRAJLA",
    "monitoring": "İZLEME AKTİF",
    "readyLive": "LIVE İÇİN HAZIR",
    "disclaimer": "Sinyaller tahmindir, garanti değildir. Son karar kullanıcıya aittir."
  },
  "el": {
    "models": "μοντέλα",
    "guideQuick": "ΓΡΗΓΟΡΟΣ ΟΔΗΓΟΣ",
    "initializingCamera": "Αρχικοποίηση κάμερας…",
    "cameraPermission": "Απαιτείται πρόσβαση στην κάμερα για LIVE ανάλυση γραφήματος.",
    "allowCamera": "ΝΑ ΕΠΙΤΡΑΠΕΙ Η ΚΑΜΕΡΑ",
    "quickStart": "ΓΡΗΓΟΡΗ ΕΝΑΡΞΗ",
    "quickSub": "3 βήματα για σωστή LIVE ανάλυση",
    "step1": "Στρέψτε την κάμερα στο γράφημα συναλλαγών της δεύτερης συσκευής.",
    "step2": "Κρατήστε ορατά κεριά, τιμές και timeframe και κλειδώστε το πλαίσιο.",
    "step3": "Ξεκινήστε CAMERA LIVE και περιμένετε επιβεβαίωση 2/2 πριν BUY ή SELL.",
    "understood": "ΚΑΤΑΛΑΒΑ",
    "timeframeAuto": "ΑΥΤΟΜΑΤΟ TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "ΠΑΤΗΣΤΕ ΓΙΑ ΕΝΑΡΞΗ",
    "activeAuto": "ΕΝΕΡΓΗ • ΑΥΤΟΜΑΤΗ ΑΝΑΛΥΣΗ",
    "directionWindow": "ΠΑΡΑΘΥΡΟ ΚΑΤΕΥΘΥΝΣΗΣ",
    "lastSignals": "ΤΕΛΕΥΤΑΙΑ ΣΗΜΑΤΑ",
    "history": "ΙΣΤΟΡΙΚΟ",
    "stats": "ΣΤΑΤΙΣΤΙΚΑ",
    "journal": "ΗΜΕΡΟΛΟΓΙΟ",
    "wait": "ΑΝΑΜΟΝΗ",
    "delete": "ΔΙΑΓΡΑΦΗ",
    "result": "LIVE ΑΠΟΤΕΛΕΣΜΑ",
    "model": "Μοντέλο",
    "score": "Βαθμός",
    "expiry": "Προτεινόμενη λήξη",
    "direction": "Εκτιμώμενη διάρκεια κατεύθυνσης",
    "camera": "Κάμερα",
    "engine": "Μηχανή",
    "ready": "ΕΤΟΙΜΟ",
    "initializing": "ΑΡΧΙΚΟΠΟΙΗΣΗ",
    "chartDetected": "ΕΝΤΟΠΙΣΤΗΚΕ ΓΡΑΦΗΜΑ • ΑΝΑΛΥΣΗ ΕΝΕΡΓΗ",
    "chartMissing": "ΔΕΝ ΕΝΤΟΠΙΣΤΗΚΕ ΓΡΑΦΗΜΑ",
    "waitingChart": "ΑΝΑΜΟΝΗ ΓΡΑΦΗΜΑΤΟΣ",
    "positionCamera": "ΤΟΠΟΘΕΤΗΣΤΕ ΚΑΜΕΡΑ",
    "frameFixed": "ΠΛΑΙΣΙΟ ΚΛΕΙΔΩΜΕΝΟ",
    "frameHere": "ΤΟΠΟΘΕΤΗΣΤΕ ΤΟ ΓΡΑΦΗΜΑ ΕΔΩ",
    "monitoring": "ΠΑΡΑΚΟΛΟΥΘΗΣΗ ΕΝΕΡΓΗ",
    "readyLive": "ΕΤΟΙΜΟ ΓΙΑ LIVE",
    "disclaimer": "Τα σήματα είναι εκτιμήσεις, όχι εγγυήσεις. Η τελική απόφαση ανήκει στον χρήστη."
  },
  "hu": {
    "models": "modell",
    "guideQuick": "GYORS ÚTMUTATÓ",
    "initializingCamera": "Kamera inicializálása…",
    "cameraPermission": "A LIVE grafikon elemzéséhez kamera-hozzáférés szükséges.",
    "allowCamera": "KAMERA ENGEDÉLYEZÉSE",
    "quickStart": "GYORS INDÍTÁS",
    "quickSub": "3 lépés a helyes LIVE elemzéshez",
    "step1": "Irányítsd a kamerát a második eszköz kereskedési grafikonjára.",
    "step2": "Tartsd láthatóan a gyertyákat, árakat és timeframe-et, majd rögzítsd a képet.",
    "step3": "Indítsd el a CAMERA LIVE-ot, és várd meg a 2/2 megerősítést BUY vagy SELL előtt.",
    "understood": "ÉRTEM",
    "timeframeAuto": "AUTOMATIKUS TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "ÉRINTSD MEG AZ INDÍTÁSHOZ",
    "activeAuto": "AKTÍV • AUTOMATIKUS ELEMZÉS",
    "directionWindow": "IRÁNYABLAK",
    "lastSignals": "LEGUTÓBBI JELZÉSEK",
    "history": "ELŐZMÉNYEK",
    "stats": "STATISZTIKÁK",
    "journal": "NAPLÓ",
    "wait": "VÁRJ",
    "delete": "TÖRLÉS",
    "result": "LIVE EREDMÉNY",
    "model": "Modell",
    "score": "Pontszám",
    "expiry": "Ajánlott lejárat",
    "direction": "Becsült irányidőtartam",
    "camera": "Kamera",
    "engine": "Motor",
    "ready": "KÉSZ",
    "initializing": "INICIALIZÁLÁS",
    "chartDetected": "GRAFIKON ÉSZLELVE • ELEMZÉS AKTÍV",
    "chartMissing": "GRAFIKON NEM ÉSZLELHETŐ",
    "waitingChart": "GRAFIKONRA VÁR",
    "positionCamera": "HELYEZD EL A KAMERÁT",
    "frameFixed": "KÉP RÖGZÍTVE",
    "frameHere": "KERETEZD IDE A GRAFIKONT",
    "monitoring": "FIGYELÉS AKTÍV",
    "readyLive": "KÉSZ A LIVE-RA",
    "disclaimer": "A jelzések becslések, nem garanciák. A végső döntést a felhasználó hozza meg."
  },
  "cs": {
    "models": "modelů",
    "guideQuick": "RYCHLÝ PRŮVODCE",
    "initializingCamera": "Inicializace kamery…",
    "cameraPermission": "Pro LIVE analýzu grafu je nutný přístup ke kameře.",
    "allowCamera": "POVOLIT KAMERU",
    "quickStart": "RYCHLÝ START",
    "quickSub": "3 kroky pro správnou LIVE analýzu",
    "step1": "Namiřte kameru na obchodní graf na druhém zařízení.",
    "step2": "Nechte viditelné svíčky, ceny a timeframe a poté zafixujte záběr.",
    "step3": "Spusťte CAMERA LIVE a před BUY nebo SELL počkejte na potvrzení 2/2.",
    "understood": "ROZUMÍM",
    "timeframeAuto": "AUTO TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "KLEPNĚTE PRO START",
    "activeAuto": "AKTIVNÍ • AUTOMATICKÁ ANALÝZA",
    "directionWindow": "OKNO SMĚRU",
    "lastSignals": "POSLEDNÍ SIGNÁLY",
    "history": "HISTORIE",
    "stats": "STATISTIKY",
    "journal": "DENÍK",
    "wait": "ČEKEJ",
    "delete": "SMAZAT",
    "result": "LIVE VÝSLEDEK",
    "model": "Model",
    "score": "Skóre",
    "expiry": "Doporučené vypršení",
    "direction": "Odhadovaná délka směru",
    "camera": "Kamera",
    "engine": "Modul",
    "ready": "PŘIPRAVENO",
    "initializing": "INICIALIZACE",
    "chartDetected": "GRAF ROZPOZNÁN • ANALÝZA AKTIVNÍ",
    "chartMissing": "GRAF NEROZPOZNÁN",
    "waitingChart": "ČEKÁM NA GRAF",
    "positionCamera": "NASTAVTE KAMERU",
    "frameFixed": "ZÁBĚR UZAMČEN",
    "frameHere": "UMÍSTĚTE GRAF SEM",
    "monitoring": "SLEDOVÁNÍ AKTIVNÍ",
    "readyLive": "PŘIPRAVENO PRO LIVE",
    "disclaimer": "Signály jsou odhady, nikoli záruky. Konečné rozhodnutí je na uživateli."
  },
  "sk": {
    "models": "modelov",
    "guideQuick": "RÝCHLY SPRIEVODCA",
    "initializingCamera": "Inicializácia kamery…",
    "cameraPermission": "Na LIVE analýzu grafu je potrebný prístup ku kamere.",
    "allowCamera": "POVOLIŤ KAMERU",
    "quickStart": "RÝCHLY ŠTART",
    "quickSub": "3 kroky pre správnu LIVE analýzu",
    "step1": "Namierte kameru na obchodný graf na druhom zariadení.",
    "step2": "Nechajte viditeľné sviečky, ceny a timeframe a potom uzamknite záber.",
    "step3": "Spustite CAMERA LIVE a pred BUY alebo SELL počkajte na potvrdenie 2/2.",
    "understood": "ROZUMIEM",
    "timeframeAuto": "AUTO TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "KLEPNITE PRE ŠTART",
    "activeAuto": "AKTÍVNA • AUTOMATICKÁ ANALÝZA",
    "directionWindow": "OKNO SMERU",
    "lastSignals": "POSLEDNÉ SIGNÁLY",
    "history": "HISTÓRIA",
    "stats": "ŠTATISTIKY",
    "journal": "DENNÍK",
    "wait": "ČAKAŤ",
    "delete": "VYMAZAŤ",
    "result": "LIVE VÝSLEDOK",
    "model": "Model",
    "score": "Skóre",
    "expiry": "Odporúčané vypršanie",
    "direction": "Odhadované trvanie smeru",
    "camera": "Kamera",
    "engine": "Modul",
    "ready": "PRIPRAVENÉ",
    "initializing": "INICIALIZÁCIA",
    "chartDetected": "GRAF ROZPOZNANÝ • ANALÝZA AKTÍVNA",
    "chartMissing": "GRAF NEROZPOZNANÝ",
    "waitingChart": "ČAKÁM NA GRAF",
    "positionCamera": "NASTAVTE KAMERU",
    "frameFixed": "ZÁBER UZAMKNUTÝ",
    "frameHere": "UMIESTNITE GRAF SEM",
    "monitoring": "SLEDOVANIE AKTÍVNE",
    "readyLive": "PRIPRAVENÉ NA LIVE",
    "disclaimer": "Signály sú odhady, nie záruky. Konečné rozhodnutie je na používateľovi."
  },
  "bg": {
    "models": "модела",
    "guideQuick": "БЪРЗО РЪКОВОДСТВО",
    "initializingCamera": "Инициализиране на камерата…",
    "cameraPermission": "За LIVE анализ на графиката е нужен достъп до камерата.",
    "allowCamera": "РАЗРЕШИ КАМЕРА",
    "quickStart": "БЪРЗ СТАРТ",
    "quickSub": "3 стъпки за правилен LIVE анализ",
    "step1": "Насочете камерата към търговската графика на второто устройство.",
    "step2": "Оставете свещите, цените и timeframe видими и заключете кадъра.",
    "step3": "Стартирайте CAMERA LIVE и изчакайте потвърждение 2/2 преди BUY или SELL.",
    "understood": "РАЗБРАХ",
    "timeframeAuto": "АВТО TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "НАТИСНЕТЕ ЗА СТАРТ",
    "activeAuto": "АКТИВНА • АВТОМАТИЧЕН АНАЛИЗ",
    "directionWindow": "ПРОЗОРЕЦ НА ПОСОКАТА",
    "lastSignals": "ПОСЛЕДНИ СИГНАЛИ",
    "history": "ИСТОРИЯ",
    "stats": "СТАТИСТИКА",
    "journal": "ДНЕВНИК",
    "wait": "ИЗЧАКАЙ",
    "delete": "ИЗТРИЙ",
    "result": "LIVE РЕЗУЛТАТ",
    "model": "Модел",
    "score": "Оценка",
    "expiry": "Препоръчано изтичане",
    "direction": "Прогнозна продължителност на посоката",
    "camera": "Камера",
    "engine": "Модул",
    "ready": "ГОТОВО",
    "initializing": "ИНИЦИАЛИЗАЦИЯ",
    "chartDetected": "ГРАФИКА ОТКРИТА • АНАЛИЗЪТ Е АКТИВЕН",
    "chartMissing": "ГРАФИКА НЕ Е ОТКРИТА",
    "waitingChart": "ИЗЧАКВАМ ГРАФИКА",
    "positionCamera": "ПОЗИЦИОНИРАЙТЕ КАМЕРАТА",
    "frameFixed": "КАДЪРЪТ Е ЗАКЛЮЧЕН",
    "frameHere": "ПОСТАВЕТЕ ГРАФИКАТА ТУК",
    "monitoring": "НАБЛЮДЕНИЕТО Е АКТИВНО",
    "readyLive": "ГОТОВО ЗА LIVE",
    "disclaimer": "Сигналите са оценки, не гаранции. Крайното решение е на потребителя."
  },
  "sr": {
    "models": "modela",
    "guideQuick": "BRZI VODIČ",
    "initializingCamera": "Pokretanje kamere…",
    "cameraPermission": "Pristup kameri je potreban za LIVE analizu grafikona.",
    "allowCamera": "DOZVOLI KAMERU",
    "quickStart": "BRZI START",
    "quickSub": "3 koraka za ispravnu LIVE analizu",
    "step1": "Usmerite kameru na trgovački grafikon na drugom uređaju.",
    "step2": "Držite sveće, cene i timeframe vidljivim, zatim zaključajte kadar.",
    "step3": "Pokrenite CAMERA LIVE i sačekajte potvrdu 2/2 pre BUY ili SELL.",
    "understood": "RAZUMEM",
    "timeframeAuto": "AUTO TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "DODIRNITE ZA START",
    "activeAuto": "AKTIVNA • AUTOMATSKA ANALIZA",
    "directionWindow": "PROZOR SMERA",
    "lastSignals": "POSLEDNJI SIGNALI",
    "history": "ISTORIJA",
    "stats": "STATISTIKA",
    "journal": "DNEVNIK",
    "wait": "SAČEKAJ",
    "delete": "OBRIŠI",
    "result": "LIVE REZULTAT",
    "model": "Model",
    "score": "Ocena",
    "expiry": "Preporučeni istek",
    "direction": "Procenjeno trajanje smera",
    "camera": "Kamera",
    "engine": "Motor",
    "ready": "SPREMNO",
    "initializing": "INICIJALIZACIJA",
    "chartDetected": "GRAFIKON OTKRIVEN • ANALIZA AKTIVNA",
    "chartMissing": "GRAFIKON NIJE OTKRIVEN",
    "waitingChart": "ČEKAM GRAFIKON",
    "positionCamera": "POSTAVITE KAMERU",
    "frameFixed": "KADAR ZAKLJUČAN",
    "frameHere": "POSTAVITE GRAFIKON OVDE",
    "monitoring": "PRAĆENJE AKTIVNO",
    "readyLive": "SPREMNO ZA LIVE",
    "disclaimer": "Signali su procene, ne garancije. Konačnu odluku donosi korisnik."
  },
  "hr": {
    "models": "modela",
    "guideQuick": "BRZI VODIČ",
    "initializingCamera": "Pokretanje kamere…",
    "cameraPermission": "Pristup kameri potreban je za LIVE analizu grafikona.",
    "allowCamera": "DOPUSTI KAMERU",
    "quickStart": "BRZI START",
    "quickSub": "3 koraka za ispravnu LIVE analizu",
    "step1": "Usmjerite kameru na trgovački grafikon na drugom uređaju.",
    "step2": "Držite svijeće, cijene i timeframe vidljivima, zatim zaključajte kadar.",
    "step3": "Pokrenite CAMERA LIVE i pričekajte potvrdu 2/2 prije BUY ili SELL.",
    "understood": "RAZUMIJEM",
    "timeframeAuto": "AUTO TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "DODIRNITE ZA START",
    "activeAuto": "AKTIVNA • AUTOMATSKA ANALIZA",
    "directionWindow": "PROZOR SMJERA",
    "lastSignals": "POSLJEDNJI SIGNALI",
    "history": "POVIJEST",
    "stats": "STATISTIKA",
    "journal": "DNEVNIK",
    "wait": "PRIČEKAJ",
    "delete": "IZBRIŠI",
    "result": "LIVE REZULTAT",
    "model": "Model",
    "score": "Ocjena",
    "expiry": "Preporučeni istek",
    "direction": "Procijenjeno trajanje smjera",
    "camera": "Kamera",
    "engine": "Motor",
    "ready": "SPREMNO",
    "initializing": "INICIJALIZACIJA",
    "chartDetected": "GRAFIKON OTKRIVEN • ANALIZA AKTIVNA",
    "chartMissing": "GRAFIKON NIJE OTKRIVEN",
    "waitingChart": "ČEKAM GRAFIKON",
    "positionCamera": "POSTAVITE KAMERU",
    "frameFixed": "KADAR ZAKLJUČAN",
    "frameHere": "POSTAVITE GRAFIKON OVDJE",
    "monitoring": "PRAĆENJE AKTIVNO",
    "readyLive": "SPREMNO ZA LIVE",
    "disclaimer": "Signali su procjene, a ne jamstva. Konačnu odluku donosi korisnik."
  },
  "sl": {
    "models": "modelov",
    "guideQuick": "HITRI VODNIK",
    "initializingCamera": "Inicializacija kamere…",
    "cameraPermission": "Dostop do kamere je potreben za LIVE analizo grafikona.",
    "allowCamera": "DOVOLI KAMERO",
    "quickStart": "HITER ZAČETEK",
    "quickSub": "3 koraki za pravilno LIVE analizo",
    "step1": "Usmerite kamero na trgovalni grafikon na drugi napravi.",
    "step2": "Ohranite sveče, cene in timeframe vidne ter zaklenite kader.",
    "step3": "Zaženite CAMERA LIVE in počakajte na potrditev 2/2 pred BUY ali SELL.",
    "understood": "RAZUMEM",
    "timeframeAuto": "SAMODEJNI TIMEFRAME",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "DOTAKNITE SE ZA ZAČETEK",
    "activeAuto": "AKTIVNA • SAMODEJNA ANALIZA",
    "directionWindow": "OKNO SMERI",
    "lastSignals": "ZADNJI SIGNALI",
    "history": "ZGODOVINA",
    "stats": "STATISTIKA",
    "journal": "DNEVNIK",
    "wait": "POČAKAJ",
    "delete": "IZBRIŠI",
    "result": "LIVE REZULTAT",
    "model": "Model",
    "score": "Ocena",
    "expiry": "Priporočeni iztek",
    "direction": "Ocenjeno trajanje smeri",
    "camera": "Kamera",
    "engine": "Motor",
    "ready": "PRIPRAVLJENO",
    "initializing": "INICIALIZACIJA",
    "chartDetected": "GRAFIKON ZAZNAN • ANALIZA AKTIVNA",
    "chartMissing": "GRAFIKON NI ZAZNAN",
    "waitingChart": "ČAKAM NA GRAFIKON",
    "positionCamera": "POSTAVITE KAMERO",
    "frameFixed": "KADER ZAKLENJEN",
    "frameHere": "UMESTITE GRAFIKON SEM",
    "monitoring": "SPREMLJANJE AKTIVNO",
    "readyLive": "PRIPRAVLJENO ZA LIVE",
    "disclaimer": "Signali so ocene, ne jamstva. Končna odločitev je uporabnikova."
  },
  "ar": {
    "models": "نماذج",
    "guideQuick": "دليل سريع",
    "initializingCamera": "جارٍ تهيئة الكاميرا…",
    "cameraPermission": "يلزم الوصول إلى الكاميرا لتحليل الرسم البياني LIVE.",
    "allowCamera": "السماح بالكاميرا",
    "quickStart": "بدء سريع",
    "quickSub": "3 خطوات لتحليل LIVE صحيح",
    "step1": "وجّه الكاميرا إلى مخطط التداول على الجهاز الثاني.",
    "step2": "أبقِ الشموع والأسعار والإطار الزمني ظاهرة ثم ثبّت الإطار.",
    "step3": "شغّل CAMERA LIVE وانتظر تأكيد 2/2 قبل BUY أو SELL.",
    "understood": "فهمت",
    "timeframeAuto": "الإطار الزمني تلقائي",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "اضغط للبدء",
    "activeAuto": "نشط • تحليل تلقائي",
    "directionWindow": "نافذة الاتجاه",
    "lastSignals": "أحدث الإشارات",
    "history": "السجل",
    "stats": "الإحصاءات",
    "journal": "اليوميات",
    "wait": "انتظر",
    "delete": "حذف",
    "result": "نتيجة LIVE",
    "model": "النموذج",
    "score": "النتيجة",
    "expiry": "الانتهاء الموصى به",
    "direction": "المدة التقديرية للاتجاه",
    "camera": "الكاميرا",
    "engine": "المحرك",
    "ready": "جاهز",
    "initializing": "جارٍ التهيئة",
    "chartDetected": "تم اكتشاف الرسم • التحليل نشط",
    "chartMissing": "لم يتم اكتشاف الرسم",
    "waitingChart": "بانتظار الرسم",
    "positionCamera": "ضع الكاميرا",
    "frameFixed": "تم تثبيت الإطار",
    "frameHere": "ضع الرسم هنا",
    "monitoring": "المراقبة نشطة",
    "readyLive": "جاهز لـ LIVE",
    "disclaimer": "الإشارات تقديرات وليست ضمانات. القرار النهائي للمستخدم."
  },
  "he": {
    "models": "מודלים",
    "guideQuick": "מדריך מהיר",
    "initializingCamera": "מאתחל מצלמה…",
    "cameraPermission": "נדרשת גישה למצלמה לצורך ניתוח גרף LIVE.",
    "allowCamera": "אפשר מצלמה",
    "quickStart": "התחלה מהירה",
    "quickSub": "3 שלבים לניתוח LIVE תקין",
    "step1": "כוון את המצלמה לגרף המסחר במכשיר השני.",
    "step2": "השאר נרות, מחירים וטווח זמן גלויים ונעל את המסגרת.",
    "step3": "הפעל CAMERA LIVE והמתן לאישור 2/2 לפני BUY או SELL.",
    "understood": "הבנתי",
    "timeframeAuto": "טווח זמן אוטומטי",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "הקש להתחלה",
    "activeAuto": "פעיל • ניתוח אוטומטי",
    "directionWindow": "חלון כיוון",
    "lastSignals": "אותות אחרונים",
    "history": "היסטוריה",
    "stats": "סטטיסטיקה",
    "journal": "יומן",
    "wait": "המתן",
    "delete": "מחק",
    "result": "תוצאת LIVE",
    "model": "מודל",
    "score": "ציון",
    "expiry": "פקיעה מומלצת",
    "direction": "משך כיוון משוער",
    "camera": "מצלמה",
    "engine": "מנוע",
    "ready": "מוכן",
    "initializing": "אתחול",
    "chartDetected": "גרף זוהה • ניתוח פעיל",
    "chartMissing": "גרף לא זוהה",
    "waitingChart": "ממתין לגרף",
    "positionCamera": "מקם מצלמה",
    "frameFixed": "מסגרת נעולה",
    "frameHere": "מקם את הגרף כאן",
    "monitoring": "ניטור פעיל",
    "readyLive": "מוכן ל-LIVE",
    "disclaimer": "האותות הם הערכות ולא הבטחות. ההחלטה הסופית היא של המשתמש."
  },
  "zh": {
    "models": "模型",
    "guideQuick": "快速指南",
    "initializingCamera": "正在初始化相机…",
    "cameraPermission": "LIVE 图表分析需要相机权限。",
    "allowCamera": "允许相机",
    "quickStart": "快速开始",
    "quickSub": "正确 LIVE 分析的 3 个步骤",
    "step1": "将相机对准第二台设备上的交易图表。",
    "step2": "保持K线、价格和时间周期可见，然后锁定画面。",
    "step3": "启动 CAMERA LIVE，在 BUY 或 SELL 前等待 2/2 确认。",
    "understood": "明白了",
    "timeframeAuto": "自动时间周期",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "点击开始",
    "activeAuto": "已开启 • 自动分析",
    "directionWindow": "方向窗口",
    "lastSignals": "最新信号",
    "history": "历史",
    "stats": "统计",
    "journal": "日志",
    "wait": "等待",
    "delete": "删除",
    "result": "LIVE 结果",
    "model": "模型",
    "score": "评分",
    "expiry": "建议到期时间",
    "direction": "预计方向持续时间",
    "camera": "相机",
    "engine": "引擎",
    "ready": "就绪",
    "initializing": "初始化中",
    "chartDetected": "已检测到图表 • 分析中",
    "chartMissing": "未检测到图表",
    "waitingChart": "等待图表",
    "positionCamera": "调整相机位置",
    "frameFixed": "画面已锁定",
    "frameHere": "将图表置于此处",
    "monitoring": "监控中",
    "readyLive": "已准备 LIVE",
    "disclaimer": "信号仅为估计，不构成保证。最终决定由用户作出。"
  },
  "ja": {
    "models": "モデル",
    "guideQuick": "クイックガイド",
    "initializingCamera": "カメラを初期化しています…",
    "cameraPermission": "LIVEチャート分析にはカメラへのアクセスが必要です。",
    "allowCamera": "カメラを許可",
    "quickStart": "クイックスタート",
    "quickSub": "正しいLIVE分析の3ステップ",
    "step1": "2台目の端末の取引チャートにカメラを向けます。",
    "step2": "ローソク足、価格、時間足を表示したままフレームを固定します。",
    "step3": "CAMERA LIVEを開始し、BUYまたはSELLの前に2/2確認を待ちます。",
    "understood": "了解",
    "timeframeAuto": "自動時間足",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "タップして開始",
    "activeAuto": "稼働中 • 自動分析",
    "directionWindow": "方向ウィンドウ",
    "lastSignals": "最新シグナル",
    "history": "履歴",
    "stats": "統計",
    "journal": "ジャーナル",
    "wait": "待機",
    "delete": "削除",
    "result": "LIVE結果",
    "model": "モデル",
    "score": "スコア",
    "expiry": "推奨期限",
    "direction": "推定方向持続時間",
    "camera": "カメラ",
    "engine": "エンジン",
    "ready": "準備完了",
    "initializing": "初期化中",
    "chartDetected": "チャート検出 • 分析中",
    "chartMissing": "チャート未検出",
    "waitingChart": "チャート待機中",
    "positionCamera": "カメラを調整",
    "frameFixed": "フレーム固定",
    "frameHere": "ここにチャートを合わせる",
    "monitoring": "監視中",
    "readyLive": "LIVE準備完了",
    "disclaimer": "シグナルは推定であり保証ではありません。最終判断はユーザーが行います。"
  },
  "ko": {
    "models": "모델",
    "guideQuick": "빠른 가이드",
    "initializingCamera": "카메라 초기화 중…",
    "cameraPermission": "LIVE 차트 분석을 위해 카메라 접근이 필요합니다.",
    "allowCamera": "카메라 허용",
    "quickStart": "빠른 시작",
    "quickSub": "정확한 LIVE 분석을 위한 3단계",
    "step1": "두 번째 기기의 거래 차트에 카메라를 향하세요.",
    "step2": "캔들, 가격, 타임프레임이 보이도록 한 뒤 프레임을 고정하세요.",
    "step3": "CAMERA LIVE를 시작하고 BUY 또는 SELL 전 2/2 확인을 기다리세요.",
    "understood": "확인",
    "timeframeAuto": "자동 타임프레임",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "탭하여 시작",
    "activeAuto": "활성 • 자동 분석",
    "directionWindow": "방향 창",
    "lastSignals": "최근 신호",
    "history": "기록",
    "stats": "통계",
    "journal": "저널",
    "wait": "대기",
    "delete": "삭제",
    "result": "LIVE 결과",
    "model": "모델",
    "score": "점수",
    "expiry": "권장 만료",
    "direction": "예상 방향 지속시간",
    "camera": "카메라",
    "engine": "엔진",
    "ready": "준비됨",
    "initializing": "초기화 중",
    "chartDetected": "차트 감지됨 • 분석 활성",
    "chartMissing": "차트가 감지되지 않음",
    "waitingChart": "차트 대기 중",
    "positionCamera": "카메라 위치 조정",
    "frameFixed": "프레임 고정됨",
    "frameHere": "차트를 여기에 맞추세요",
    "monitoring": "모니터링 활성",
    "readyLive": "LIVE 준비됨",
    "disclaimer": "신호는 추정치이며 보장이 아닙니다. 최종 결정은 사용자가 합니다."
  },
  "hi": {
    "models": "मॉडल",
    "guideQuick": "त्वरित मार्गदर्शिका",
    "initializingCamera": "कैमरा प्रारंभ हो रहा है…",
    "cameraPermission": "LIVE चार्ट विश्लेषण के लिए कैमरा अनुमति आवश्यक है।",
    "allowCamera": "कैमरा अनुमति दें",
    "quickStart": "त्वरित शुरुआत",
    "quickSub": "सही LIVE विश्लेषण के लिए 3 चरण",
    "step1": "कैमरे को दूसरे डिवाइस के ट्रेडिंग चार्ट की ओर रखें।",
    "step2": "कैंडल, कीमतें और टाइमफ्रेम दिखाई दें, फिर फ्रेम लॉक करें।",
    "step3": "CAMERA LIVE शुरू करें और BUY/SELL से पहले 2/2 पुष्टि की प्रतीक्षा करें।",
    "understood": "समझ गया",
    "timeframeAuto": "ऑटो टाइमफ्रेम",
    "cameraLive": "CAMERA LIVE",
    "tapStart": "शुरू करने के लिए टैप करें",
    "activeAuto": "सक्रिय • स्वचालित विश्लेषण",
    "directionWindow": "दिशा विंडो",
    "lastSignals": "नवीनतम संकेत",
    "history": "इतिहास",
    "stats": "आँकड़े",
    "journal": "जर्नल",
    "wait": "प्रतीक्षा",
    "delete": "हटाएँ",
    "result": "LIVE परिणाम",
    "model": "मॉडल",
    "score": "स्कोर",
    "expiry": "अनुशंसित समाप्ति",
    "direction": "अनुमानित दिशा अवधि",
    "camera": "कैमरा",
    "engine": "इंजन",
    "ready": "तैयार",
    "initializing": "प्रारंभ हो रहा है",
    "chartDetected": "चार्ट मिला • विश्लेषण सक्रिय",
    "chartMissing": "चार्ट नहीं मिला",
    "waitingChart": "चार्ट की प्रतीक्षा",
    "positionCamera": "कैमरा रखें",
    "frameFixed": "फ्रेम लॉक",
    "frameHere": "चार्ट को यहाँ रखें",
    "monitoring": "निगरानी सक्रिय",
    "readyLive": "LIVE के लिए तैयार",
    "disclaimer": "संकेत अनुमान हैं, गारंटी नहीं। अंतिम निर्णय उपयोगकर्ता का है।"
  }
} as const;

type TranslationKey = keyof typeof translations.en;

function normalizeLanguage(code?: string | null): SupportedLanguage {
  const raw = String(code || 'en').toLowerCase().split(/[-_]/)[0];
  return (SUPPORTED_LANGUAGES as readonly string[]).includes(raw) ? raw as SupportedLanguage : 'en';
}

export function useAppLocalization() {
  const locales = useLocales();
  const primary = locales?.[0];
  const systemLanguage = normalizeLanguage(primary?.languageCode);
  const regionCode = primary?.regionCode || null;
  const [overrideLanguage, setOverrideLanguageState] = useState<SupportedLanguage | null>(null);
  const [languageLoaded, setLanguageLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_OVERRIDE_KEY)
      .then((value) => {
        if (value && (SUPPORTED_LANGUAGES as readonly string[]).includes(value)) {
          setOverrideLanguageState(value as SupportedLanguage);
        }
      })
      .finally(() => setLanguageLoaded(true));
  }, []);

  const languageCode = overrideLanguage || systemLanguage;
  const languageTag = overrideLanguage || primary?.languageTag || languageCode;

  const setLanguage = async (language: SupportedLanguage | 'auto') => {
    if (language === 'auto') {
      setOverrideLanguageState(null);
      await AsyncStorage.removeItem(LANGUAGE_OVERRIDE_KEY);
    } else {
      setOverrideLanguageState(language);
      await AsyncStorage.setItem(LANGUAGE_OVERRIDE_KEY, language);
    }
  };

  const t = useMemo(() => {
    return (key: TranslationKey): string => {
      const table = translations[languageCode] as Record<string, string>;
      return table[key] || translations.en[key] || key;
    };
  }, [languageCode]);

  return {
    t,
    languageCode,
    regionCode,
    languageTag,
    systemLanguage,
    overrideLanguage,
    languageLoaded,
    setLanguage,
    languageMode: overrideLanguage ? 'manual' as const : 'auto' as const,
  };
}
